"""create order and position tables

Revision ID: 6a8f5623ba5d
Revises: 1fd78598cb2d
Create Date: 2026-09-03 15:35:12.431167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a8f5623ba5d'
down_revision: Union[str, Sequence[str], None] = '1fd78598cb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table( "position",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column("trading_symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("buy_order_id", sa.Integer(), nullable=False),
        sa.Column("sell_order_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("buy_price", sa.Float(), nullable=False),
        sa.Column("sell_price", sa.Float(), nullable=True),
        sa.Column("buy_timestamp", sa.DateTime(), nullable=False),
        sa.Column("sell_timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=True),
        sa.Column("pnl_percent", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["buy_order_id"], ["order.id"]),
        sa.ForeignKeyConstraint(["sell_order_id"], ["order.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_trading_symbol"), "position", ["trading_symbol"])




def downgrade() -> None:
    op.drop_index(op.f("ix_position_trading_symbol"), table_name="position")
    op.drop_table("position")

    # ### end Alembic commands ###


