"""create order_details stock_table api_logs

Revision ID: 5ca050ad2e20
Revises: 
Create Date: 2026-08-25 12:11:53.175478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ca050ad2e20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('placement_batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instrument_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disclosed_quantity', sa.Integer(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('is_amo', sa.Boolean(), nullable=False),
    sa.Column('slice', sa.Boolean(), nullable=False),
    sa.Column('market_protection', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_details_order_id'), ['order_id'], unique=True)

    op.create_table('stock_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty_purchased', sa.Integer(), nullable=False),
    sa.Column('avg_purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.Column('avg_selling_price', sa.Float(), nullable=True),
    sa.Column('sell_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buy_charges', sa.Float(), nullable=False),
    sa.Column('sell_charges', sa.Float(), nullable=False),
    sa.Column('net_profit_before_tax', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('profit_after_tax', sa.Float(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_table_instrument_key'), ['instrument_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_table_instrument_key'))

    op.drop_table('stock_table')
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_details_order_id'))

    op.drop_table('order_details')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
