"""add buy_amount sell_amount to stock_table

Revision ID: 7137663ed464
Revises: 5ca050ad2e20
Create Date: 2026-08-25 12:38:36.963179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7137663ed464'
down_revision: Union[str, Sequence[str], None] = '5ca050ad2e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sell_amount', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_table', schema=None) as batch_op:
        batch_op.drop_column('sell_amount')
        batch_op.drop_column('buy_amount')

    # ### end Alembic commands ###
