"""add payload to api_log

Revision ID: 7451c774c1d9
Revises: 9f56575d1bbe
Create Date: 2026-08-25 15:27:53.583184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7451c774c1d9'
down_revision: Union[str, Sequence[str], None] = '9f56575d1bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.drop_column('payload')

    # ### end Alembic commands ###
