"""add bought_on sold_on to stock_table

Revision ID: 9c509fc8c383
Revises: 7137663ed464
Create Date: 2026-08-25 13:01:03.918267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c509fc8c383'
down_revision: Union[str, Sequence[str], None] = '7137663ed464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sold_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_table', schema=None) as batch_op:
        batch_op.drop_column('sold_on')
        batch_op.drop_column('bought_on')

    # ### end Alembic commands ###
