import os
from pathlib import Path

APPNAME = os.getenv("APPNAME")
assets_path = Path(__file__).parent.parent
instrument_file = assets_path.joinpath(os.getenv("INSTRUMENT_FILE"))
instrument_pickle_file = assets_path.joinpath(os.getenv("INSTRUMENT_FILE_PICKEL"))

SANDBOX_UPSTOX_URL = os.getenv("SANDBOX_UPSTOX_URL")
UPSTOX_URL = os.getenv("UPSTOX_URL")
UPSTOX_HF_API_URL = os.getenv("UPSTOX_HF_API_URL")

LOADED_ENV = os.getenv("LOADED_ENV")

SANDBOX_UPSTOX_CLIENT_ID = os.getenv("SANDBOX_UPSTOX_CLIENT_ID")
SANDBOX_UPSTOX_CLIENT_SECRET = os.getenv("SANDBOX_UPSTOX_CLIENT_SECRET")
SANDBOX_ACCESS_TOKEN = os.getenv("SANDBOX_ACCESS_TOKEN")

PROD_UPSTOX_CLIENT_ID = os.getenv("PROD_UPSTOX_CLIENT_ID")
PROD_UPSTOX_CLIENT_SECRET = os.getenv("PROD_UPSTOX_CLIENT_SECRET")
PROD_ACCESS_TOKEN = os.getenv("PROD_ACCESS_TOKEN")

UPSTOX_CLIENT_ID = PROD_UPSTOX_CLIENT_ID if LOADED_ENV == "SANDBOX" else SANDBOX_UPSTOX_CLIENT_ID
UPSTOX_CLIENT_SECRET = PROD_UPSTOX_CLIENT_SECRET if LOADED_ENV == "SANDBOX" else SANDBOX_UPSTOX_CLIENT_SECRET
ACCESS_TOKEN = PROD_ACCESS_TOKEN if LOADED_ENV == "SANDBOX" else SANDBOX_ACCESS_TOKEN

UPSTOX_REDIRECT_URI = os.getenv("UPSTOX_REDIRECT_URI")





