LOGIN_URL= "/v2/login/authorization/dialog"
AUTH_DIALOG_URL= "/v2/login/authorization/dialog"
GET_TOKEN_URL = "/v2/login/authorization/token"
PROFILE_URL = "/v2/user/profile"
PLACE_ORDER_URL ="/v3/order/place"
